### ISSUE TITLE
IOS测试出现一个问题,但我不确定是f2,微信还是Apple的问题

### ISSUE THREAD

**Issue by LeeeMooo** [antvis/wx-f2#8]
1. 我的需求是实现一个和官网[区域图(存在空值)](https://antv.alipay.com/zh-cn/f2/3.x/demo/area/area-none.html)类似的图, 我的X轴是时间 类似于 ##2018-05-31 16:22:57##
2. 模拟器测试正常!
3. 模拟器远程调试 **安卓** **IOS**都正常!
4. 模拟器预览 安卓正常, **IOS**错误
模拟器正常样式
![模拟器正常](https://user-images.githubusercontent.com/23691333/40771843-026eb5bc-64f1-11e8-9395-8a9184c3dacf.jpg)

![IOS报错](https://user-images.githubusercontent.com/23691333/40771342-af479b84-64ef-11e8-94aa-83f51adf88d8.jpg)
> 安卓微信版本6.6.6
> IOS微信版本6.6.6, 6.6.7
> X轴尝试过 'YYYY-MM-DD HH:mm:ss' 'HH:mm:ss' 'HH:mm' 全部报错如上图
实在是找不到解决办法,所以来求证一下!

**Comment by simaQ** [comment]
恩，这个报错信息是 F2 抛出的，你能否把能复现这个错误信息的代码（包括数据）贴给偶？ 我定位下~~~

**Comment by LeeeMooo** [comment]
[demo.zip](https://github.com/antvis/wx-f2/files/2057554/demo.zip)
代码打包了, 数据里面有一部分

**Comment by simaQ** [comment]
奇怪咧，你的demo 我都没有报错。。。 你看下你的 F2 版本号是多少？ 

另外，如果是时间类型的数据的话，我建议使用时间戳或者完整的格式 'YYYY-MM-DD HH:mm:ss'，然后在使用 chart.source() 那里声明下 type: 'timeCat'

**Comment by LeeeMooo** [comment]
我直接pull了一遍,F2应该是最新的

情况是这样的, 这个表需要的数据是数据库当天的所有数据, 原来的操作是描点连线就完事了类似于这种 [连续曲线图](https://antv.alipay.com/zh-cn/f2/3.x/demo/area/series.html) 

但现在需求是没有数据的地方不连线,就是断层图, 但数据库里面的数据不是连续的(比如说上一个数据时间是2018-06-01 11:55:00, 下一个可能是2018-06-01 15:55:00),这两个点就不能连线

我想到的办法是前端手动填充数据,2018-06-01 11:55:00 + 1min ---> 2018-06-01 15:55:00(数据都设置为整点, 如果以秒级为单位的话, 数据填充量太大了) 这中间的value = null  这样就绘出断层图了
(这样描述应该很清晰了吧)
> 但是为什么报错了呢... 应该和前面的曲线图是一样的啊 就是多了一些空数据

> 你是模拟器点击*预览*也没报错吗?(小声)

> 或者有没有什么好的办法 不填充空数据绘制断层图的_(:з」∠)_

**Comment by simaQ** [comment]
我真机以及预览都看了，么有报错。你的思路是没有问题的。

你把你处理后的数据给我吧，就是能够产生这个报错的问题的代码和数据，如果有啥不方便的，你把数据字段啥的改改，这样偶才好定位~~~~

**Comment by simaQ** [comment]
找到原因了，如果传进来的数据 value 字段全部是 null 就会导致这个问题。比如：

```js
var data = [
   { type: "湿度/%", value: null, date: "2018-06-01 11:09:00" },
   { type: "温度/℃", value: null, date: "2018-06-01 11:09:00" }
];
```
是 F2 内部在数据处理模块没有处理好，我马上修复一下，感谢反馈！！！！

**Comment by simaQ** [comment]
在 @antv/f2@3.1.9-beta.2 这个版本里面修复了，你可以 download 更新一下  f2-canvas/lib 下的 f2.js

**Comment by LeeeMooo** [comment]
很抱歉又打扰你, 3.1.9-beta2[unpgk](https://unpkg.com/@antv/f2@3.1.9-beta.2/build/f2.js)替换链接找到了(自己编译还没下载完,npm install 有点慢)
现在没报错了, 但是是这样的
![875580622](https://user-images.githubusercontent.com/23691333/40837718-ee5fcb14-65cd-11e8-97c9-d18400751ae4.jpg)
Y轴没数据
...(｡•ˇ‸ˇ•｡) ...

**Comment by simaQ** [comment]
这个是符合预期的，因为你的Y轴的数据都是 null。如果你觉得这样的展现体验不好，你可以判断下数据状态，全部为 null 的话在页面上放个提示





来自钉钉专属商务邮箱------------------------------------------------------------------发件人：LeeeMooo<notifications@github.com>日　期：2018年06月01日 19:26:45收件人：antvis/wx-f2<wx-f2@noreply.github.com>抄　送：章伟星(再飞)<zaifei.zwx@alibaba-inc.com>; State change<state_change@noreply.github.com>主　题：Re: [antvis/wx-f2] IOS测试出现一个问题,但我不确定是f2,微信还是Apple的问题 (#8)很抱歉又打扰你, 3.1.9-beta2unpgk替换链接找到了(自己编译还没下载完,npm install 有点慢)

现在没报错了, 但是是这样的



Y轴没数据

...(｡•ˇ‸ˇ•｡) ...

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/antvis/wx-f2/issues/8#issuecomment-393852617","url":"https://github.com/antvis/wx-f2/issues/8#issuecomment-393852617","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/antvis/wx-f2","title":"antvis/wx-f2","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/antvis/wx-f2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LeeeMooo in #8: 很抱歉又打扰你, 3.1.9-beta2[unpgk](https://unpkg.com/@antv/f2@3.1.9-beta.2/build/f2.js)替换链接找到了(自己编译还没下载完,npm install 有点慢)\r\n现在没报错了, 但是是这样的\r\n![875580622](https://user-images.githubusercontent.com/23691333/40837718-ee5fcb14-65cd-11e8-97c9-d18400751ae4.jpg)\r\nY轴没数据\r\n...(｡•ˇ‸ˇ•｡) ...\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/antvis/wx-f2/issues/8#issuecomment-393852617"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [antvis/wx-f2] IOS测试出现一个问题,但我不确定是f2,微信还是Apple的问题 (#8)",
"sections": [
{
"text": "",
"activityTitle": "**LeeeMooo**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@LeeeMooo",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"antvis/wx-f2\",\n\"issueId\": 8,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/antvis/wx-f2/issues/8#issuecomment-393852617"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 340955744\n}"
}
],
"themeColor": "26292E"
}

**Comment by simaQ** [comment]
你检查下是不是你前端进行数据处理的时候把所有的数据都设置为 null 了





来自钉钉专属商务邮箱------------------------------------------------------------------发件人：章伟星(再飞)<zaifei.zwx@antfin.com>日　期：2018年06月01日 19:31:45收件人：antvis/wx-f2<reply@reply.github.com>; antvis/wx-f2<wx-f2@noreply.github.com>抄　送：章伟星(再飞)<zaifei.zwx@alibaba-inc.com>; State change<state_change@noreply.github.com>主　题：回复： [antvis/wx-f2] IOS测试出现一个问题,但我不确定是f2,微信还是Apple的问题 (#8)这个是符合预期的，因为你的Y轴的数据都是 null。如果你觉得这样的展现体验不好，你可以判断下数据状态，全部为 null 的话在页面上放个提示





来自钉钉专属商务邮箱------------------------------------------------------------------发件人：LeeeMooo<notifications@github.com>日　期：2018年06月01日 19:26:45收件人：antvis/wx-f2<wx-f2@noreply.github.com>抄　送：章伟星(再飞)<zaifei.zwx@alibaba-inc.com>; State change<state_change@noreply.github.com>主　题：Re: [antvis/wx-f2] IOS测试出现一个问题,但我不确定是f2,微信还是Apple的问题 (#8)很抱歉又打扰你, 3.1.9-beta2unpgk替换链接找到了(自己编译还没下载完,npm install 有点慢)

现在没报错了, 但是是这样的



Y轴没数据

...(｡•ˇ‸ˇ•｡) ...

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/antvis/wx-f2/issues/8#issuecomment-393852617","url":"https://github.com/antvis/wx-f2/issues/8#issuecomment-393852617","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/antvis/wx-f2","title":"antvis/wx-f2","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/antvis/wx-f2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LeeeMooo in #8: 很抱歉又打扰你, 3.1.9-beta2[unpgk](https://unpkg.com/@antv/f2@3.1.9-beta.2/build/f2.js)替换链接找到了(自己编译还没下载完,npm install 有点慢)\r\n现在没报错了, 但是是这样的\r\n![875580622](https://user-images.githubusercontent.com/23691333/40837718-ee5fcb14-65cd-11e8-97c9-d18400751ae4.jpg)\r\nY轴没数据\r\n...(｡•ˇ‸ˇ•｡) ...\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/antvis/wx-f2/issues/8#issuecomment-393852617"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [antvis/wx-f2] IOS测试出现一个问题,但我不确定是f2,微信还是Apple的问题 (#8)",
"sections": [
{
"text": "",
"activityTitle": "**LeeeMooo**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@LeeeMooo",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"antvis/wx-f2\",\n\"issueId\": 8,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/antvis/wx-f2/issues/8#issuecomment-393852617"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 340955744\n}"
}
],
"themeColor": "26292E"
}

**Comment by LeeeMooo** [comment]
不是啊 数据是正常中间穿插着null,这样才能画出断层图呀,全是null就没有绘图的必要了

**Comment by simaQ** [comment]
当你的 Y 轴数据全是 null 的时候就会出现你截图的情况，所以我在想是不是传给 chart 对象的源数据的问题，你调试下看看调用到 chart.source(data) 的时候，data 是什么样的吧。

**Comment by LeeeMooo** [comment]
我直接在f2里面打印的data
![1](https://user-images.githubusercontent.com/23691333/40869065-66f763ec-6647-11e8-8e61-6a02ce2ed828.png)
这是微信开发工具打印的
![2](https://user-images.githubusercontent.com/23691333/40869073-7b4c774c-6647-11e8-84d7-f93d94084ca3.png)

这是iPhone打印的
![3](https://user-images.githubusercontent.com/23691333/40869080-87aad484-6647-11e8-838c-da381b74fd50.jpg)

iPhone里面**value**字段消失了。。。系统bug吗? 11.4.1

>姐姐救救我~
